# Shrimply a list of all the different item types, icons are the same as the name
itemIds = [
    "grapes",
    "watermelon",
    "Pepper",
    "carrots",
    "Corn",
    "sweet-potato",
    "bread",
    "butter",
    "milk",
    "egg",
    "maple-syrup",
    "soda",
    "onion",
    "orange",
    "strawberry",
    "coconut",
    "instant-noodles",
    "soy",
    "pasta",
    "tomato",
    "chocolate",
    "chocBag",
]